Added environment file.

diff --git a/run b/run
--- a/run
+++ b/run
@@ -11,8 +11,9 @@ function PrintUsage()
 	echo -e "	-no-run, -dno	do not run the program for any diagonal, just compile"
 	echo -e "	-d1, -d45b	run the program for diagonal 45b-56t"
 	echo -e "	-d2, -d45t	run the program for diagonal 45t-56b"
-	echo -e "	-d12, -d21	run the program for both diagonals"
+	echo -e "	-dboth			run the program for both diagonals"
 	echo -e "	-dc, -dcomb	run the program in combined diagonals"
+	echo -e "	-danti			run the program in anti-diagonals"
 	echo -e "	-O <option>	pass the option to the program"
 	echo -e "	-no-bckg	do no run compilation and programs in background"
 }
@@ -22,12 +23,19 @@ function PrintUsage()
 diag_45b_56t="y"
 diag_45t_56b="y"
 diag_combined="y"
+
 diag_45b_56b="n"
 diag_45t_56t="n"
 
 runInBackground="y"
 
+lxbatch="n"
+submit="n"
+
 rcIncompatibleDiagonal=123
+
+bsub_options="pool>5000"
+bsub_queue="8nh"
 
 #----------------------------------------------------------------------------------------------------
 
@@ -48,23 +56,46 @@ function RunOneDiagonal()
 	label="$tag @ $dir:$diag"
 	log="${tag}_${diag}.log_run"
 
-	echo "$label > running$optionsStr"
-	{ time "./$exe_file" "$diag" $options ; } &> "$log"
-	errCode="$?"
-	case "$errCode" in
-		0)
-			echo "$label > done"
-			;;
+	if [ "$lxbatch" == "y" ]
+	then
+		local cwd=`pwd -P`
+		local job_dir="$cwd"
+		local job_file=".${tag}_${diag}.job"
+		local job_log_file=".${tag}_${diag}.log_job"
 
-		$rcIncompatibleDiagonal)
-			rm "$log"
-			;;
+		cat "$top_dir/job_template" | sed "\
+				s|\$JOB_DIR|$job_dir|; \
+				s|\$JOB_LOG_FILE|$job_log_file|; \
+				s|\$COMMAND|{ time \"./$exe_file\" \"$diag\" $options ; } \&> \"$log\"|; \
+			" > "$job_file"
+		chmod u+x "$job_file"
 
-		*)
-			echo "$label > run error"
-			if [ "$par_more" -eq 1 ]; then tail -n 30 "$log"; fi
-			;;
-	esac
+		if [ "$submit" == "y" ]
+		then
+			result=`bsub -R "$bsub_options" -q "$bsub_queue" -o /dev/null -e /dev/null "$cwd/$job_file"`
+			echo "$label > $result"
+		else
+			echo "$label > would be submitted (use -submit option)"
+		fi
+	else
+		echo "$label > running$optionsStr"
+		{ time "./$exe_file" "$diag" $options ; } &> "$log"
+		errCode="$?"
+		case "$errCode" in
+			0)
+				echo "$label > done"
+				;;
+	
+			$rcIncompatibleDiagonal)
+				rm "$log"
+				;;
+	
+			*)
+				echo "$label > run error ($errCode)"
+				if [ "$par_more" -eq 1 ]; then tail -n 5 "$log"; fi
+				;;
+		esac
+	fi
 }
 
 #----------------------------------------------------------------------------------------------------
@@ -79,14 +110,15 @@ function RunOneDir()
 	local par_more="$3"
 	local options="$4"
 
-	local top_dir=`pwd`
+	top_dir=`pwd`
 
 	cp "$input" "$dir/$src_file"
 	cd "$dir"
+
+	GSL_DIR="/afs/cern.ch/cms/slc6_amd64_gcc481/external/gsl/1.10/"
 	
 	echo "$tag @ $dir > compiling"
-	GSL_DIR="/afs/cern.ch/cms/slc6_amd64_gcc481/external/gsl/1.10"
-	g++ -O3 -std=c++11 -Wall -Wextra -Werror -g -ggdb\
+	g++ -O3 -g -Wall -Wextra -Werror --std=c++11\
 			-I"$top_dir" \
 			`root-config --libs` -lMinuit -lMinuit2 `root-config --cflags` \
 			-I"$CMSSW_BASE/src" \
@@ -137,6 +169,8 @@ function RunOneDir()
 	then
 		RunOneDiagonal "$tag" "$dir" "$par_more" "45t_56t" "$options" &
 	fi
+
+	cd - &> /dev/null
 }
 
 #----------------------------------------------------------------------------------------------------
@@ -218,6 +252,15 @@ do
 
 		"-no-bckg")
 			runInBackground="n"
+			;;
+
+		"-lxbatch")
+			lxbatch="y"
+			;;
+
+		"-submit")
+			lxbatch="y"
+			submit="y"
 			;;
 
 		*)
